### ISSUE TITLE
Change response models with prefix: Response

### ISSUE THREAD

**Issue by mjovanc** [kryptokrona/kryptokrona-kotlin-sdk#22]

**Comment by dev-divyansh** [comment]
could you provide more information on this

**Comment by mjovanc** [comment]
@dev-divyansh Certainly, the models in the library Kryptokrona-http inside here: https://github.com/kryptokrona/kryptokrona-kotlin-sdk/tree/master/kryptokrona-http/src/main/kotlin/org/kryptokrona/sdk/http/model/response needs to be refactored so that every data class and file name are using the format of `SomeNameResponse`. 

Currently we are not using that and it would be more clearer when passing around these data class object in the code what its purpose is. If it's a response or request object.

**Comment by dev-divyansh** [comment]
@mjovanc  I would like to work on this

**Comment by mjovanc** [comment]
@dev-divyansh Just make a fork and then commit and then send a pull request whenever you are done. Please checkout the Wiki pages here to be informed about the project here. Thanks and happy coding!

**Comment by mjovanc** [comment]
Fixed.
